name: camera
description: A Flutter plugin for controlling the camera. Supports previewing
  the camera feed, capturing images and video, and streaming image buffers to
  Dart.
repository: https://github.com/flutter/packages/tree/main/packages/camera/camera
issue_tracker: https://github.com/flutter/flutter/issues?q=is%3Aissue+is%3Aopen+label%3A%22p%3A+camera%22
version: 0.10.5+9
publish_to: none

environment:
  sdk: ^3.1.0
  flutter: ">=3.13.0"

flutter:
  plugin:
    platforms:
      android:
        default_package: camera_android
      ios:
        default_package: camera_avfoundation
      web:
        default_package: camera_web

dependencies:
  camera_android: # ^0.10.7
    git:
      url: https://github.com/kaciula/packages.git
      path: packages/camera/camera_android
      ref: a509028d5aca8fe763822f6efa71d284757fa26e
    # path: ../camera_android
  camera_avfoundation: # ^0.9.13
    git:
      url: https://github.com/kaciula/packages.git
      path: packages/camera/camera_avfoundation
      ref: a509028d5aca8fe763822f6efa71d284757fa26e
    # path: ../camera_avfoundation
  camera_platform_interface: # ^2.5.0
    git:
      url: https://github.com/kaciula/packages.git
      path: packages/camera/camera_platform_interface
      ref: a509028d5aca8fe763822f6efa71d284757fa26e
    # path: ../camera_platform_interface
  camera_web: # ^0.3.1
    git:
      url: https://github.com/kaciula/packages.git
      path: packages/camera/camera_web
      ref: 937d5a890dfd8670f7a19e12bccffc46bc9ab15c
    # path: ../camera_web
  flutter:
    sdk: flutter
  flutter_plugin_android_lifecycle: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: 5.4.4
  plugin_platform_interface: ^2.1.7

topics:
  - camera
