name: camera_web_integration_tests
publish_to: none

environment:
  sdk: ^3.1.0
  flutter: ">=3.13.0"

dependencies:
  camera_platform_interface: # ^2.1.0
    git:
      url: https://github.com/kaciula/packages.git
      path: packages/camera/camera_platform_interface
      ref: d285c381e8f7c2911af93ad337ac300f47a40efe
  camera_web:
    path: ../
  flutter:
    sdk: flutter

dev_dependencies:
  async: ^2.5.0
  cross_file: ^0.3.1
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  mocktail: 0.3.0
