name: camera_android
description: Android implementation of the camera plugin.
repository: https://github.com/flutter/packages/tree/main/packages/camera/camera_android
issue_tracker: https://github.com/flutter/flutter/issues?q=is%3Aissue+is%3Aopen+label%3A%22p%3A+camera%22
publish_to: none

version: 0.10.8+16

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

flutter:
  plugin:
    implements: camera
    platforms:
      android:
        package: io.flutter.plugins.camera
        pluginClass: CameraPlugin
        dartPluginClass: AndroidCamera

dependencies:
  camera_platform_interface: # ^2.5.0
    git:
      url: https://github.com/kaciula/packages.git
      path: packages/camera/camera_platform_interface
      ref: 61e1800adc5f6295e36fd5e1618c007fb7259390
    # path: ../camera_platform_interface
  flutter:
    sdk: flutter
  flutter_plugin_android_lifecycle: ^2.0.2
  stream_transform: ^2.0.0

dev_dependencies:
  async: ^2.5.0
  flutter_test:
    sdk: flutter

topics:
  - camera
