name: camera_web
description: A Flutter plugin for getting information about and controlling the camera on Web.
repository: https://github.com/flutter/packages/tree/main/packages/camera/camera_web
issue_tracker: https://github.com/flutter/flutter/issues?q=is%3Aissue+is%3Aopen+label%3A%22p%3A+camera%22
version: 0.3.2+4
publish_to: "none"

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=3.13.0"

flutter:
  plugin:
    implements: camera
    platforms:
      web:
        pluginClass: CameraPlugin
        fileName: camera_web.dart

dependencies:
  camera_platform_interface: # ^2.3.1
    git:
      url: https://github.com/kaciula/packages.git
      path: packages/camera/camera_platform_interface
      ref: f5974d5e5ee53b797db2759c975121b053f7a9e4
    # path: ../camera_platform_interface
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  stream_transform: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

topics:
  - camera
